In [8]:
# ==== Cell 1 : fully manual lexicon with hard-coded 6-way conjugations =====
import json
from pathlib import Path

# ------------------------------------------------------------------ pronouns
PRON_FR = ["je","tu","il","nous","vous","ils"]
PRON_NL = ["ik","jij","hij","wij","jullie","zijpl"]

# ------------------------------------------------------------------ manual verb conjugations
VERBS = {
    "fr": {
        # key: {
        #   "present": {pronoun: form, …},
        #   "participle": "<past-participle>"
        # }
        "mange": {
            "present": {
                "je":    "mange",
                "tu":    "manges",
                "il":    "mange",
                "nous":  "mangeons",
                "vous":  "mangez",
                "ils":   "mangent"
            },
            "participle": "mangé"
        },
        "voit": {
            "present": {
                "je":    "vois",
                "tu":    "vois",
                "il":    "voit",
                "nous":  "voyons",
                "vous":  "voyez",
                "ils":   "voient"
            },
            "participle": "vu"
        },
        "aime": {
            "present": {
                "je":    "aime",
                "tu":    "aimes",
                "il":    "aime",
                "nous":  "aimons",
                "vous":  "aimez",
                "ils":   "aiment"
            },
            "participle": "aimé"
        },
        "cherche": {
            "present": {
                "je":    "cherche",
                "tu":    "cherches",
                "il":    "cherche",
                "nous":  "cherchons",
                "vous":  "cherchez",
                "ils":   "cherchent"
            },
            "participle": "cherché"
        },
        "aide": {
            "present": {
                "je":    "aide",
                "tu":    "aides",
                "il":    "aide",
                "nous":  "aidons",
                "vous":  "aidez",
                "ils":   "aident"
            },
            "participle": "aidé"
        },
        "suit": {
            "present": {
                "je":    "suis",
                "tu":    "suis",
                "il":    "suit",
                "nous":  "suivons",
                "vous":  "suivez",
                "ils":   "suivent"
            },
            "participle": "suivi"
        },
        "frappe": {
            "present": {
                "je":    "frappe",
                "tu":    "frappes",
                "il":    "frappe",
                "nous":  "frapons",
                "vous":  "frappez",
                "ils":   "frappent"
            },
            "participle": "frappé"
        },
        "porte": {
            "present": {
                "je":    "porte",
                "tu":    "portes",
                "il":    "porte",
                "nous":  "portons",
                "vous":  "portez",
                "ils":   "portent"
            },
            "participle": "porté"
        },
        "embrasse": {
            "present": {
                "je":    "embrasse",
                "tu":    "embrasses",
                "il":    "embrasse",
                "nous":  "embrassons",
                "vous":  "embrassez",
                "ils":   "embrassent"
            },
            "participle": "embrassé"
        },
        "chasse": {
            "present": {
                "je":    "chasse",
                "tu":    "chasses",
                "il":    "chasse",
                "nous":  "chassons",
                "vous":  "chassez",
                "ils":   "chassent"
            },
            "participle": "chassé"
        },
        "observe": {
            "present": {
                "je":    "observe",
                "tu":    "observes",
                "il":    "observe",
                "nous":  "observons",
                "vous":  "observez",
                "ils":   "observent"
            },
            "participle": "observé"
        },
        "soigne": {
            "present": {
                "je":    "soigne",
                "tu":    "soignes",
                "il":    "soigne",
                "nous":  "soignons",
                "vous":  "soignez",
                "ils":   "soignent"
            },
            "participle": "soigné"
        },
        "poursuit": {
            "present": {
                "je":    "poursuis",
                "tu":    "poursuis",
                "il":    "poursuit",
                "nous":  "poursuivons",
                "vous":  "poursuivez",
                "ils":   "poursuivent"
            },
            "participle": "poursuivi"
        },
        "attaque": {
            "present": {
                "je":    "attaque",
                "tu":    "attaques",
                "il":    "attaque",
                "nous":  "attaquons",
                "vous":  "attaquez",
                "ils":   "attaquent"
            },
            "participle": "attaqué"
        },
        "sauve": {
            "present": {
                "je":    "sauve",
                "tu":    "sauves",
                "il":    "sauve",
                "nous":  "sauvons",
                "vous":  "sauvez",
                "ils":   "sauvent"
            },
            "participle": "sauvé"
        },
        "réconforte": {
            "present": {
                "je":    "réconforte",
                "tu":    "réconfortes",
                "il":    "réconforte",
                "nous":  "réconfortons",
                "vous":  "réconfortez",
                "ils":   "réconfortent"
            },
            "participle": "réconforté"
        },
        "repousse": {
            "present": {
                "je":    "repousse",
                "tu":    "repousses",
                "il":    "repousse",
                "nous":  "repoussons",
                "vous":  "repoussez",
                "ils":   "repoussent"
            },
            "participle": "repoussé"
        },
        "regarde": {
            "present": {
                "je":    "regarde",
                "tu":    "regardes",
                "il":    "regarde",
                "nous":  "regardons",
                "vous":  "regardez",
                "ils":   "regardent"
            },
            "participle": "regardé"
        },
        "ignore": {
            "present": {
                "je":    "ignore",
                "tu":    "ignores",
                "il":    "ignore",
                "nous":  "ignorons",
                "vous":  "ignorez",
                "ils":   "ignorent"
            },
            "participle": "ignoré"
        }
    },
    "nl": {
        "eet": {
            "present": {
                "ik":    "eet",
                "jij":   "eet",
                "hij":   "eet",
                "wij":   "eten",
                "jullie":"eten",
                "zijpl": "eten"
            },
            "participle": "gegeten"
        },
        "ziet": {
            "present": {
                "ik":    "zie",
                "jij":   "ziet",
                "hij":   "ziet",
                "wij":   "zien",
                "jullie":"zien",
                "zijpl": "zien"
            },
            "participle": "gezien"
        },
        "mag": {
            "present": {
                "ik":    "mag",
                "jij":   "mag",
                "hij":   "mag",
                "wij":   "mogen",
                "jullie":"mogen",
                "zijpl": "mogen"
            },
            "participle": "gemogen"
        },
        "zoekt": {
            "present": {
                "ik":    "zoek",
                "jij":   "zoekt",
                "hij":   "zoekt",
                "wij":   "zoeken",
                "jullie":"zoeken",
                "zijpl": "zoeken"
            },
            "participle": "gezocht"
        },
        "helpt": {
            "present": {
                "ik":    "help",
                "jij":   "helpt",
                "hij":   "helpt",
                "wij":   "helpen",
                "jullie":"helpen",
                "zijpl": "helpen"
            },
            "participle": "geholpen"
        },
        "volgt": {
            "present": {
                "ik":    "volg",
                "jij":   "volgt",
                "hij":   "volgt",
                "wij":   "volgen",
                "jullie":"volgen",
                "zijpl": "volgen"
            },
            "participle": "gevolgd"
        },
        "slaat": {
            "present": {
                "ik":    "sla",
                "jij":   "slaat",
                "hij":   "slaat",
                "wij":   "slaan",
                "jullie":"slaan",
                "zijpl": "slaan"
            },
            "participle": "geslagen"
        },
        "draagt": {
            "present": {
                "ik":    "draag",
                "jij":   "draagt",
                "hij":   "draagt",
                "wij":   "dragen",
                "jullie":"dragen",
                "zijpl": "dragen"
            },
            "participle": "gedragen"
        },
        "zoent": {
            "present": {
                "ik":    "zoen",
                "jij":   "zoent",
                "hij":   "zoent",
                "wij":   "zoenen",
                "jullie":"zoenen",
                "zijpl": "zoenen"
            },
            "participle": "gezoend"
        },
        "jaagt": {
            "present": {
                "ik":    "jaag",
                "jij":   "jaagt",
                "hij":   "jaagt",
                "wij":   "jagen",
                "jullie":"jagen",
                "zijpl": "jagen"
            },
            "participle": "gejaagd"
        },
        "observeert": {
            "present": {
                "ik":    "observeer",
                "jij":   "observeert",
                "hij":   "observeert",
                "wij":   "observeren",
                "jullie":"observeren",
                "zijpl": "observeren"
            },
            "participle": "geobserveerd"
        },
        "verzorgt": {
            "present": {
                "ik":    "verzorg",
                "jij":   "verzorgt",
                "hij":   "verzorgt",
                "wij":   "verzorgen",
                "jullie":"verzorgen",
                "zijpl": "verzorgen"
            },
            "participle": "verzorgd"
        },
        "achtervolgt": {
            "present": {
                "ik":    "achtervolg",
                "jij":   "achtervolgt",
                "hij":   "achtervolgt",
                "wij":   "achtervolgen",
                "jullie":"achtervolgen",
                "zijpl": "achtervolgen"
            },
            "participle": "achtervolgd"
        },
        "valt": {
            "present": {
                "ik":    "val",
                "jij":   "valt",
                "hij":   "valt",
                "wij":   "vallen",
                "jullie":"vallen",
                "zijpl": "vallen"
            },
            "participle": "aangevallen"
        },
        "redt": {
            "present": {
                "ik":    "red",
                "jij":   "redt",
                "hij":   "redt",
                "wij":   "redden",
                "jullie":"redden",
                "zijpl": "redden"
            },
            "participle": "gered"
        },
        "troost": {
            "present": {
                "ik":    "troost",
                "jij":   "troost",
                "hij":   "troost",
                "wij":   "troosten",
                "jullie":"troosten",
                "zijpl": "troosten"
            },
            "participle": "getroost"
        },
        "duwt": {
            "present": {
                "ik":    "duw",
                "jij":   "duwt",
                "hij":   "duwt",
                "wij":   "duwen",
                "jullie":"duwen",
                "zijpl": "duwen"
            },
            "participle": "geduwd"
        },
        "bekijkt": {
            "present": {
                "ik":    "bekijk",
                "jij":   "bekijkt",
                "hij":   "bekijkt",
                "wij":   "bekijken",
                "jullie":"bekijken",
                "zijpl": "bekijken"
            },
            "participle": "bekeken"
        },
        "negeert": {
            "present": {
                "ik":    "negeer",
                "jij":   "negeert",
                "hij":   "negeert",
                "wij":   "negeren",
                "jullie":"negeren",
                "zijpl": "negeren"
            },
            "participle": "genegeerd"
        }
    }
}

# ------------ small sanity check -------------------------------------------
print("FR sample – 'mange':", VERBS["fr"]["mange"])
print("NL sample – 'eet'  :", VERBS["nl"]["eet"])

# ------------ save lexicon --------------------------------------------------
lexicon = {
    "DET":     {"fr":"le","nl":"de"},
    "DET_PL":  {"fr":"les","nl":"de"},
    "NOUNS": {
        'fr': {
            'chien': 'chiens','loup': 'loups','chat': 'chats','tigre': 'tigres',
            'singe': 'singes','cheval': 'chevaux','souris': 'souris',
            'éléphant': 'éléphants','renard': 'renards','oiseau': 'oiseaux',
            'enfant': 'enfants','docteur': 'docteurs','fille': 'filles',
            'garçon': 'garçons','femme': 'femmes','homme': 'hommes',
            'professeur':'professeurs','ami':'amis','ennemi':'ennemis'
        },
        'nl': {
            'hond': 'honden','leeuw': 'leeuwen','kat': 'katten','tijger':'tijgers',
            'aap': 'apen','paard': 'paarden','muis': 'muizen','olifant':'olifanten',
            'vos': 'vossen','vogel': 'vogels','kind':'kinderen','dokter':'dokters',
            'meisje':'meisjes','jongen':'jongens','vrouw':'vrouwen','man':'mannen',
            'leraar':'leraars','vriend':'vrienden','vijand':'vijanden'
        }
    },
    "AUX": {
        "fr": dict(zip(PRON_FR, ["ai","as","a","avons","avez","ont"])),
        "nl": dict(zip(PRON_NL, ["heb","hebt","heeft","hebben","hebben","hebben"]))
    },
    "VERBS": VERBS
}

Path("data").mkdir(exist_ok=True)
with open("data/lexicon.json","w", encoding="utf-8") as f:
    json.dump(lexicon, f, ensure_ascii=False, indent=2)
print("✓ fully manual lexicon saved to data/lexicon.json")

FR sample – 'mange': {'present': {'je': 'mange', 'tu': 'manges', 'il': 'mange', 'nous': 'mangeons', 'vous': 'mangez', 'ils': 'mangent'}, 'participle': 'mangé'}
NL sample – 'eet'  : {'present': {'ik': 'eet', 'jij': 'eet', 'hij': 'eet', 'wij': 'eten', 'jullie': 'eten', 'zijpl': 'eten'}, 'participle': 'gegeten'}
✓ fully manual lexicon saved to data/lexicon.json

In [7]:
# ==== Cell 2 : build corpus with unseen (lang, subject, verb) split =========
import json, itertools, random, re, pandas as pd
from pathlib import Path

lex = json.load(open("data/lexicon.json"))
DET, DET_PL = lex["DET"], lex["DET_PL"]
NOUNS, AUX, VERBS = lex["NOUNS"], lex["AUX"], lex["VERBS"]

def sentence_pron(lang:str, pron:str, obj:str, vkey:str):
    v   = VERBS[vkey]
    pres= v[lang][pron]
    part= v["part"][lang]
    if lang=="fr":
        return (f"{pron} {pres} {DET[lang]} {obj}",
                f"{pron} {AUX[lang][pron]} {part} {DET[lang]} {obj}")
    else:
        return (f"{pron} {pres} {DET[lang]} {obj}",
                f"{pron} {AUX[lang][pron]} {DET[lang]} {obj} {part}")

def sentence_noun(lang:str, subj:str, plural:bool, obj:str, vkey:str):
    v     = VERBS[vkey]
    pron  = {"fr": ("ils" if plural else "il"),
             "nl": ("zijpl" if plural else "hij")}[lang]
    pres  = v[lang][pron]
    part  = v["part"][lang]
    det_s = DET_PL[lang] if plural else DET[lang]
    det_o = DET_PL[lang] if obj in NOUNS[lang].values() else DET[lang]
    subj_form = NOUNS[lang][subj] if plural else subj
    if lang=="fr":
        return (f"{det_s} {subj_form} {pres} {det_o} {obj}",
                f"{det_s} {subj_form} {AUX[lang][pron]} {part} {det_o} {obj}")
    else:
        return (f"{det_s} {subj_form} {pres} {det_o} {obj}",
                f"{det_s} {subj_form} {AUX[lang][pron]} {det_o} {obj} {part}")

rows=[]
for lang in ("fr","nl"):
    pronouns = list(AUX[lang])
    nouns_sg = list(NOUNS[lang])
    nouns_pl = list(NOUNS[lang].values())

    for vkey in VERBS:
        # pronoun subjects
        for pron,obj in itertools.product(pronouns, nouns_sg):
            inp,tgt = sentence_pron(lang, pron, obj, vkey)
            rows.append({"input":inp,"target":tgt,"lang":lang,
                         "subj":pron,"verb":vkey})
        # noun subjects (sg + pl)
        for subj,obj in itertools.product(nouns_sg, nouns_sg):
            if subj==obj: continue
            for plural in (False, True):
                inp,tgt = sentence_noun(lang, subj, plural, obj, vkey)
                rows.append({"input":inp,"target":tgt,"lang":lang,
                             "subj":NOUNS[lang][subj] if plural else subj,
                             "verb":vkey})

df = pd.DataFrame(rows)
print("Total sentences:", len(df))

# -------- split so (lang, subj, verb) is exclusive -------------------------
keys = df[['lang','subj','verb']].apply(tuple, axis=1).unique()
random.seed(0)
test_keys = set(random.sample(list(keys), int(0.2*len(keys))))

is_test = df[['lang','subj','verb']].apply(tuple, axis=1).isin(test_keys)
test_df  = df[is_test ].reset_index(drop=True)
train_df = df[~is_test].reset_index(drop=True)
print("Train:", len(train_df), "  Test:", len(test_df))

# -------- write datasets ---------------------------------------------------
OUT = Path("data"); OUT.mkdir(exist_ok=True)
train_df.to_csv(OUT/"train.csv", index=False)
test_df.to_csv (OUT/"test.csv" , index=False)

# -------- build vocab ------------------------------------------------------
def tok(s): return re.findall(r"\w+|[^\s\w]", s)
special = ['<pad>','<sos>','<eos>','<unk>','<sep>']
vocab = special + sorted({t
          for s in train_df.input.tolist()+train_df.target.tolist()
          for t in tok(s)} - set(special))
json.dump(vocab, open(OUT/"vocab.json","w"), ensure_ascii=False, indent=2)
print("Vocab size:", len(vocab))

Total sentences: 60648
Train: 48490   Test: 12158
Vocab size: 368

# metrics

In [8]:
# ==== Cell 1 : build French / Dutch token lookup sets ======================
import json, re
from pathlib import Path

LEX = json.load(open("data/lexicon.json"))

# -- flat token lists -------------------------------------------------------
det_fr   = {"le","la","les"}                       # we only use these determiners
det_nl   = {"de","het"}                           # minimal Dutch determiners
aux_fr   = set(LEX["AUX"]["fr"].values())
aux_nl   = set(LEX["AUX"]["nl"].values())

# verbs
verb_fr  = {form for v in LEX["VERBS"].values() for form in v["fr"].values()}
verb_nl  = {form for v in LEX["VERBS"].values() for form in v["nl"].values()}
part_fr  = {v["part"]["fr"] for v in LEX["VERBS"].values()}
part_nl  = {v["part"]["nl"] for v in LEX["VERBS"].values()}

noun_fr  = set(LEX["NOUNS"]["fr"].keys()) | set(LEX["NOUNS"]["fr"].values())
noun_nl  = set(LEX["NOUNS"]["nl"].keys()) | set(LEX["NOUNS"]["nl"].values())

TOK_FR   = det_fr | aux_fr | verb_fr | part_fr | noun_fr
TOK_NL   = det_nl | aux_nl | verb_nl | part_nl | noun_nl

In [6]:
# ==== Cell 2 :  metrics (per-language token share + word order) ============
import re

def token_language_fraction(tokens):
    """
    Return dict with share of tokens that belong to each language lexicon.

        {'fr': 0.83, 'nl': 0.17}
    """
    total = len(tokens)
    fr_hits = sum(t in TOK_FR for t in tokens)
    nl_hits = sum(t in TOK_NL for t in tokens)
    # collect non hits
    non_hits = [t for t in tokens if t not in TOK_FR and t not in TOK_NL]
    return {"fr": fr_hits/total, "nl": nl_hits/total, "non_hits": non_hits}

# -------------------------------------------------------------------------
# word_order()  – robust first-noun / first-verb / second-noun classifier
# -------------------------------------------------------------------------
def word_order(tokens):
    """
    Decide constituent order using the global lookup sets already defined
    in Cell 1.

        SVO / SOV / VSO / VOS / OSV / OVS / "unknown"
    """
    noun_vocab  = noun_fr  | noun_nl               # all noun surface forms
    verb_vocab  = verb_fr  | verb_nl               # finite forms
    # (optionally count participles & auxiliaries as verbs too)
    verb_vocab |= part_fr  | part_nl | aux_fr | aux_nl

    idx_n1 = idx_v = idx_n2 = None

    # first NOUN
    for i, tok in enumerate(tokens):
        if tok in noun_vocab:
            idx_n1 = i
            break
    if idx_n1 is None:
        return "unknown"

    # first VERB after N₁
    for i in range(idx_n1 + 1, len(tokens)):
        if tokens[i] in verb_vocab:
            idx_v = i
            break
    if idx_v is None:
        return "unknown"

    # first NOUN after V
    for i in range(idx_v + 1, len(tokens)):
        if tokens[i] in noun_vocab:
            idx_n2 = i
            break
    if idx_n2 is None:
        return "unknown"

    # compose canonical order tag
    triple = sorted([(idx_n1, "S"), (idx_v, "V"), (idx_n2, "O")],
                    key=lambda x: x[0])
    return "".join(label for _, label in triple)



# --------------- demo on four sentences ------------------------------------

examples = [
    "le chien a mangé le chat",
    "les chiens ont vu les loups",
    "de hond observeert de olifant",
    "de hond heeft de olifant geobserveerd"
]

for s in examples:
    toks = re.findall(r"\w+|[^\s\w]", s.lower())
    frac = token_language_fraction(toks)
    w_order = word_order(toks)
    print(f"{s}")
    print(f"  token-match fractions: {frac}   grammar: {w_order}")

le chien a mangé le chat
  token-match fractions: {'fr': 1.0, 'nl': 0.0, 'non_hits': []}   grammar: SVO
les chiens ont vu les loups
  token-match fractions: {'fr': 1.0, 'nl': 0.0, 'non_hits': []}   grammar: SVO
de hond observeert de olifant
  token-match fractions: {'fr': 0.2, 'nl': 1.0, 'non_hits': []}   grammar: SVO
de hond heeft de olifant geobserveerd
  token-match fractions: {'fr': 0.0, 'nl': 1.0, 'non_hits': []}   grammar: SVO

# now train models.

In [ ]:
#!/usr/bin/env python
# ---------------------------------------------------------------------------
# Tiny GPT-2 tense-conversion trainer + per-language word-order / token-share
# ---------------------------------------------------------------------------
import argparse, json, re, numpy as np, pandas as pd, torch
from pathlib import Path
from tokenizers import Tokenizer
from tokenizers.models import WordLevel
from tokenizers.pre_tokenizers import Whitespace
from tokenizers.decoders import WordPiece
from transformers import (
    PreTrainedTokenizerFast,
    GPT2Config, GPT2LMHeadModel,
    Trainer, TrainingArguments,
    DataCollatorWithPadding, EarlyStoppingCallback,
    set_seed, default_data_collator          # default still used for labels pad-id
)
from transformers import DataCollatorWithPadding
import torch

class Seq2SeqPadCollator:
    def __init__(self, tokenizer, pad_to_multiple_of=8):
        self.tokenizer = tokenizer
        self.pad_to_multiple_of = pad_to_multiple_of
        
    def __call__(self, features):
        # Get max length across all features for consistent padding
        max_length = max(len(f["input_ids"]) for f in features)
        
        # Pad to multiple of pad_to_multiple_of if specified
        if self.pad_to_multiple_of is not None:
            max_length = ((max_length + self.pad_to_multiple_of - 1) // 
                         self.pad_to_multiple_of) * self.pad_to_multiple_of
        
        # Pad inputs and labels consistently to the same max_length
        batch = {}
        
        # First process input_ids and attention_mask
        batch["input_ids"] = torch.tensor([
            f["input_ids"] + [self.tokenizer.pad_token_id] * (max_length - len(f["input_ids"]))
            for f in features
        ], dtype=torch.long)
        
        batch["attention_mask"] = torch.tensor([
            f["attention_mask"] + [0] * (max_length - len(f["attention_mask"]))
            for f in features
        ], dtype=torch.long)
        
        # Then process labels, ensuring the same shape as input_ids
        batch["labels"] = torch.tensor([
            f["labels"] + [-100] * (max_length - len(f["labels"]))
            for f in features
        ], dtype=torch.long)
        
        return batch


# -------------------- CLI ---------------------------------------------------
# cli = argparse.ArgumentParser()
# cli.add_argument("--prop",   type=float, required=True)  # French share
# cli.add_argument("--run_id", type=int,   required=True)  # RNG seed / run tag
# args   = cli.parse_args()
# prop   = args.prop; run_id = args.run_id
# assert 0.0 <= prop <= 1.0
prop = 0.3
run_id = 0
# -------------------- paths & RNG ------------------------------------------
set_seed(run_id)
DATA_DIR = Path("data")
OUT_DIR  = Path(f"weights/small_p{int(prop*100):02d}_run{run_id}")
OUT_DIR.mkdir(parents=True, exist_ok=True)

# -------------------- load corpus ------------------------------------------
train_full = pd.read_csv(DATA_DIR/"train.csv")
test_df    = pd.read_csv(DATA_DIR/"test.csv")

df_fr = train_full[train_full.lang == "fr"]
df_nl = train_full[train_full.lang == "nl"]
want_fr = min(int(len(train_full)*prop), len(df_fr))
want_nl = min(len(train_full)-want_fr,      len(df_nl))

train_df = pd.concat([
    df_fr.sample(want_fr, replace=False, random_state=0),
    df_nl.sample(want_nl, replace=False, random_state=0)
]).sample(frac=1, random_state=0).reset_index(drop=True)

print(f"Train set {len(train_df)} rows  ({want_fr} FR, {want_nl} NL)")

# -------------------- tokenizer --------------------------------------------
vocab = json.load(open(DATA_DIR/"vocab.json"))
for sp in ["<pad>","<sos>","<eos>","<sep>","<unk>"]:
    if sp not in vocab: vocab.append(sp)
stoi = {t:i for i,t in enumerate(vocab)}

tok_obj = Tokenizer(WordLevel(stoi, unk_token="<unk>"))
tok_obj.pre_tokenizer = Whitespace(); tok_obj.decoder = WordPiece()
tokenizer = PreTrainedTokenizerFast(
    tokenizer_object=tok_obj,
    bos_token="<sos>", eos_token="<eos>",
    pad_token="<pad>", unk_token="<unk>", sep_token="<sep>"
)

# -------------------- dataset ----------------------------------------------
def encode_pair(pres, past):
    pres_ids = tokenizer.encode(pres, add_special_tokens=False)
    past_ids = tokenizer.encode(past, add_special_tokens=False)
    
    # Create input_ids with special tokens
    ids = [tokenizer.bos_token_id] + pres_ids + [tokenizer.sep_token_id] + past_ids + [tokenizer.eos_token_id]
    
    # Create labels with same length as input_ids
    sep_pos = 1 + len(pres_ids)
    labels = [-100] * (sep_pos + 1) + ids[sep_pos+1:]
    
    # Ensure labels has the same length as input_ids
    if len(labels) < len(ids):
        labels = labels + [-100] * (len(ids) - len(labels))
    
    return {
        "input_ids": ids,
        "attention_mask": [1] * len(ids),
        "labels": labels
    }

class PairDS(torch.utils.data.Dataset):
    def __init__(self, df):
        # keep *lists* – the collator will pad & tensorise
        self.buf = [encode_pair(r.input, r.target) for r in df.itertuples()]
    def __len__(self):  return len(self.buf)
    def __getitem__(self, i):  return self.buf[i]

train_ds, val_ds = PairDS(train_df), PairDS(test_df)

# -------------------- model -------------------------------------------------
model = GPT2LMHeadModel(GPT2Config(
        vocab_size=len(vocab), n_embd=128, n_layer=2, n_head=2,
        bos_token_id=tokenizer.bos_token_id,
        eos_token_id=tokenizer.eos_token_id,
        pad_token_id=tokenizer.pad_token_id
)).to("cuda" if torch.cuda.is_available() else "cpu")

# -------------------- metrics ----------------------------------------------
def tok_acc(eval_pred):
    logits, labels = eval_pred
    preds = np.argmax(logits[:, :-1], axis=-1)
    lbls  = labels[:, 1:]
    mask  = lbls != -100
    return {"tok_acc": float(((preds==lbls)&mask).sum()/mask.sum())}

def exact_match(eval_pred):
    logits, labels = eval_pred
    ok = ((np.argmax(logits[:, :-1], axis=-1) == labels[:,1:]) |
          (labels[:,1:] == -100)).all(axis=1)
    return {"exact_match": float(ok.mean())}

# -------------------- Trainer ----------------------------------------------
collator = Seq2SeqPadCollator(tokenizer, pad_to_multiple_of=8)

trainer = Trainer(
    model=model,
    args=TrainingArguments(
        output_dir=str(OUT_DIR),
        max_steps=2_000,
        per_device_train_batch_size=16, per_device_eval_batch_size=16,
        gradient_accumulation_steps=4,
        fp16=True,
        learning_rate=2e-4, warmup_steps=500,
        lr_scheduler_type="cosine", weight_decay=1e-2,
        eval_strategy="steps", eval_steps=1000,
        save_strategy="steps", save_steps=1000, save_total_limit=5,
        logging_steps=2000,
        load_best_model_at_end=True, metric_for_best_model="tok_acc",
        report_to="none"
    ),
    train_dataset=train_ds,
    eval_dataset=val_ds,
    data_collator=collator,
    compute_metrics=lambda ep: {**tok_acc(ep), **exact_match(ep)},
    callbacks=[EarlyStoppingCallback(early_stopping_patience=5)]
)
trainer.train()
trainer.save_model(OUT_DIR/"final")
tokenizer.save_pretrained(OUT_DIR/"final")

# -------------------- lexicon look-ups (for new metrics) -------------------
LEX = json.load(open("data/lexicon.json"))
noun_fr = set(LEX["NOUNS"]["fr"].keys()) | set(LEX["NOUNS"]["fr"].values())
noun_nl = set(LEX["NOUNS"]["nl"].keys()) | set(LEX["NOUNS"]["nl"].values())
verb_fr = {f for v in LEX["VERBS"].values() for f in v["fr"].values()}
verb_nl = {f for v in LEX["VERBS"].values() for f in v["nl"].values()}
part_fr = {v["part"]["fr"] for v in LEX["VERBS"].values()}
part_nl = {v["part"]["nl"] for v in LEX["VERBS"].values()}
aux_fr  = set(LEX["AUX"]["fr"].values())
aux_nl  = set(LEX["AUX"]["nl"].values())
TOK_FR  = noun_fr | verb_fr | part_fr | aux_fr | {"le","la","les"}
TOK_NL  = noun_nl | verb_nl | part_nl | aux_nl | {"de","het"}

def token_lang_frac(toks):
    tot = len(toks)
    return sum(t in TOK_FR for t in toks)/tot, sum(t in TOK_NL for t in toks)/tot

def word_order(toks):
    noun_v  = noun_fr | noun_nl
    verb_v  = verb_fr | verb_nl | part_fr | part_nl | aux_fr | aux_nl
    idx_n1=idx_v=idx_n2=None
    for i,t in enumerate(toks):
        if t in noun_v: idx_n1=i; break
    if idx_n1 is None: return "unknown"
    for i in range(idx_n1+1,len(toks)):
        if toks[i] in verb_v: idx_v=i; break
    if idx_v is None: return "unknown"
    for i in range(idx_v+1,len(toks)):
        if toks[i] in noun_v: idx_n2=i; break
    if idx_n2 is None: return "unknown"
    order = sorted([(idx_n1,"S"),(idx_v,"V"),(idx_n2,"O")], key=lambda x:x[0])
    return "".join(tag for _,tag in order)

# -------------------- full-test generation ---------------------------------
model.eval(); gens=[]; dv=model.device
for r in test_df.itertuples():
    prompt = f"<sos> {r.input} <sep>"
    out = model.generate(**tokenizer(prompt, return_tensors="pt").to(dv),
                         max_new_tokens=20,
                         eos_token_id=tokenizer.eos_token_id, num_beams=4)
    pred = tokenizer.decode(out[0], skip_special_tokens=False)\
           .split("<sep>")[1].replace("<eos>","").strip()
    gens.append({"input":r.input,"target":r.target,
                 "prediction":pred,"lang":r.lang})

df_gen = pd.DataFrame(gens)
df_gen.to_csv(OUT_DIR/"test_generations.csv", index=False)

# -------------------- per-language evaluation ------------------------------
metrics = {
    "train_final_step": trainer.state.global_step,
    **trainer.state.log_history[-1]          # tok_acc / exact_match on val
}

for lang in ["fr","nl"]:
    sub = df_gen[df_gen.lang==lang]
    exact = (sub.prediction.str.strip() == sub.target.str.strip()).mean()
    fr_shares, nl_shares, orders = [], [], []

    for s in sub.prediction:
        toks = re.findall(r"\w+|[^\s\w]", s.lower())
        f_share, n_share = token_lang_frac(toks)      # unpack into f_share, n_share
        fr_shares.append(f_share)                     # append into the list
        nl_shares.append(n_share)
        orders.append(word_order(toks))

    oc = pd.Series(orders).value_counts(normalize=True)
    metrics.update({
        f"{lang}_exact":     float(exact),
        f"{lang}_avg_pred_fr": float(np.mean(fr_shares)),
        f"{lang}_avg_pred_nl": float(np.mean(nl_shares)),
        f"{lang}_order_SVO":  float(oc.get("SVO",0.0)),
        f"{lang}_order_SOV":  float(oc.get("SOV",0.0)),
        f"{lang}_order_other":float(1.0 - oc.get("SVO",0.0) - oc.get("SOV",0.0))
    })

json.dump(metrics, open(OUT_DIR/"metrics.json","w"), indent=2)
print(f"✓ finished run p={prop:.1f}  outputs → {OUT_DIR}")

/n/home06/drooryck/circuits_languages_2/venv39/lib/python3.10/site-packages/tqdm/auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm

Train set 38843 rows  (14547 FR, 24296 NL)

/n/home06/drooryck/circuits_languages_2/venv39/lib/python3.10/site-packages/accelerate/accelerator.py:449: FutureWarning: `torch.cuda.amp.GradScaler(args...)` is deprecated. Please use `torch.amp.GradScaler('cuda', args...)` instead.
  self.scaler = torch.cuda.amp.GradScaler(**kwargs)
Detected kernel version 4.18.0, which is below the recommended minimum of 5.5.0; this can cause the process to hang. It is recommended to upgrade the kernel to the minimum version or higher.
`loss_type=None` was set in the config but it is unrecognised.Using the default loss: `ForCausalLMLoss`.

There were missing keys in the checkpoint model loaded: ['lm_head.weight'].

AttributeError: 'float' object has no attribute 'append'

In [3]:
#!/usr/bin/env python
# ---------------------------------------------------------------------------
# Tiny GPT-2 tense-conversion trainer + per-language word-order / token-share
# ---------------------------------------------------------------------------
import argparse
import json
import re
import numpy as np
import pandas as pd
import torch
import logging
from pathlib import Path
from tokenizers import Tokenizer
from tokenizers.models import WordLevel
from tokenizers.pre_tokenizers import Whitespace
from tokenizers.decoders import WordPiece
from transformers import (
    PreTrainedTokenizerFast,
    GPT2Config, GPT2LMHeadModel,
    Trainer, TrainingArguments,
    EarlyStoppingCallback, set_seed
)

# -------------------- Logging Setup ---------------------------------------
logging.basicConfig(
    level=logging.INFO,
    format="%(asctime)s %(levelname)s %(name)s: %(message)s",
    datefmt="%Y-%m-%d %H:%M:%S"
)
logger = logging.getLogger("TenseTrainer")
logger.info("Logger initialized")

# -------------------- CLI ---------------------------------------------------
# cli = argparse.ArgumentParser()
# cli.add_argument("--prop",   type=float, required=True, help="fraction of French data")
# cli.add_argument("--run_id", type=int,   required=True, help="random seed / run tag")
# args   = cli.parse_args()
# prop   = args.prop
# run_id = args.run_id
# assert 0.0 <= prop <= 1.0
# logger.info(f"Starting run with prop={prop}, run_id={run_id}")
prop = 0.3
run_id = 59

# -------------------- paths & RNG ------------------------------------------
set_seed(run_id)
DATA_DIR = Path("data")
OUT_DIR  = Path(f"weights/small_p{int(prop*100):02d}_run{run_id}")
OUT_DIR.mkdir(parents=True, exist_ok=True)
logger.info(f"Data dir: {DATA_DIR}, Output dir: {OUT_DIR}")

# -------------------- load corpus ------------------------------------------
logger.info("Loading CSVs")
train_full = pd.read_csv(DATA_DIR / "train.csv")
test_df    = pd.read_csv(DATA_DIR / "test.csv")

df_fr = train_full[train_full.lang == "fr"]
df_nl = train_full[train_full.lang == "nl"]
want_fr = min(int(len(train_full) * prop), len(df_fr))
want_nl = min(len(train_full) - want_fr, len(df_nl))

train_df = pd.concat([
    df_fr.sample(want_fr, replace=False, random_state=run_id),
    df_nl.sample(want_nl, replace=False, random_state=run_id)
]).sample(frac=1, random_state=run_id).reset_index(drop=True)

logger.info(f"Train set: {len(train_df)} rows ({want_fr} FR, {want_nl} NL)")

# -------------------- tokenizer --------------------------------------------
logger.info("Building tokenizer")
vocab = json.load(open(DATA_DIR / "vocab.json"))
for sp in ["<pad>","<sos>","<eos>","<sep>","<unk>"]:
    if sp not in vocab:
        vocab.append(sp)
stoi = {t:i for i,t in enumerate(vocab)}

tok_obj = Tokenizer(WordLevel(stoi, unk_token="<unk>"))
tok_obj.pre_tokenizer = Whitespace()
tok_obj.decoder = WordPiece()
tokenizer = PreTrainedTokenizerFast(
    tokenizer_object=tok_obj,
    bos_token="<sos>", eos_token="<eos>",
    pad_token="<pad>", unk_token="<unk>", sep_token="<sep>"
)
logger.info(f"Tokenizer vocab size: {len(vocab)}")

# -------------------- dataset ----------------------------------------------
logger.info("Encoding dataset pairs")
def encode_pair(pres, past):
    pres_ids = tokenizer.encode(pres, add_special_tokens=False)
    past_ids = tokenizer.encode(past, add_special_tokens=False)
    ids = [tokenizer.bos_token_id] + pres_ids + [tokenizer.sep_token_id] + past_ids + [tokenizer.eos_token_id]
    sep_pos = 1 + len(pres_ids)
    labels = [-100] * (sep_pos + 1) + ids[sep_pos+1:]
    if len(labels) < len(ids):
        labels += [-100] * (len(ids) - len(labels))
    return {"input_ids": ids, "attention_mask": [1]*len(ids), "labels": labels}

class PairDS(torch.utils.data.Dataset):
    def __init__(self, df):
        self.buf = [encode_pair(r.input, r.target) for r in df.itertuples()]
    def __len__(self):
        return len(self.buf)
    def __getitem__(self, i):
        return self.buf[i]

train_ds, val_ds = PairDS(train_df), PairDS(test_df)
logger.info(f"Train dataset size: {len(train_ds)}; Val dataset size: {len(val_ds)}")

# -------------------- collator ---------------------------------------------
logger.info("Creating Seq2SeqPadCollator")
class Seq2SeqPadCollator:
    def __init__(self, tokenizer, pad_to_multiple_of=8):
        self.tokenizer = tokenizer
        self.pad_to_multiple_of = pad_to_multiple_of

    def __call__(self, features):
        max_len = max(len(f["input_ids"]) for f in features)
        if self.pad_to_multiple_of:
            max_len = ((max_len + self.pad_to_multiple_of - 1) //
                       self.pad_to_multiple_of) * self.pad_to_multiple_of
        batch = {}
        batch["input_ids"] = torch.tensor([
            f["input_ids"] + [self.tokenizer.pad_token_id] * (max_len - len(f["input_ids"]))
            for f in features
        ], dtype=torch.long)
        batch["attention_mask"] = torch.tensor([
            f["attention_mask"] + [0] * (max_len - len(f["attention_mask"]))
            for f in features
        ], dtype=torch.long)
        batch["labels"] = torch.tensor([
            f["labels"] + [-100] * (max_len - len(f["labels"]))
            for f in features
        ], dtype=torch.long)
        return batch

collator = Seq2SeqPadCollator(tokenizer, pad_to_multiple_of=8)

# -------------------- model -------------------------------------------------
logger.info("Initializing model")
device = "cuda" if torch.cuda.is_available() else "cpu"
model = GPT2LMHeadModel(GPT2Config(
    vocab_size=len(vocab),
    n_embd=128, n_layer=2, n_head=2,
    bos_token_id=tokenizer.bos_token_id,
    eos_token_id=tokenizer.eos_token_id,
    pad_token_id=tokenizer.pad_token_id
)).to(device)

# -------------------- metrics ----------------------------------------------
logger.info("Defining metrics")
def tok_acc(eval_pred):
    logits, labels = eval_pred
    preds = np.argmax(logits[:, :-1], axis=-1)
    lbls = labels[:, 1:]
    mask = lbls != -100
    return {"tok_acc": float(((preds==lbls)&mask).sum()/mask.sum())}

def exact_match(eval_pred):
    logits, labels = eval_pred
    ok = ((np.argmax(logits[:, :-1], axis=-1) == labels[:,1:]) |
          (labels[:,1:] == -100)).all(axis=1)
    return {"exact_match": float(ok.mean())}

# -------------------- Trainer ----------------------------------------------
logger.info("Setting up Trainer")
trainer = Trainer(
    model=model,
    args=TrainingArguments(
        output_dir=str(OUT_DIR),
        max_steps=2_000,
        per_device_train_batch_size=16,
        per_device_eval_batch_size=16,
        gradient_accumulation_steps=4,
        fp16=True,
        learning_rate=2e-4,
        warmup_steps=500,
        lr_scheduler_type="cosine",
        weight_decay=1e-2,
        eval_strategy="steps",
        eval_steps=1000,
        save_strategy="steps",
        save_steps=1000,
        save_total_limit=5,
        logging_steps=2000,
        load_best_model_at_end=True,
        metric_for_best_model="tok_acc",
        report_to="none"
    ),
    train_dataset=train_ds,
    eval_dataset=val_ds,
    data_collator=collator,
    compute_metrics=lambda ep: {**tok_acc(ep), **exact_match(ep)},
    callbacks=[EarlyStoppingCallback(early_stopping_patience=5)]
)

logger.info("Starting training")
trainer.train()
logger.info("Training complete; saving model and tokenizer")
trainer.save_model(OUT_DIR / "final")
tokenizer.save_pretrained(OUT_DIR / "final")

# -------------------- lexicon look-ups --------------------------------------
logger.info("Loading lexicon for post-hoc metrics")
LEX = json.load(open(DATA_DIR / "lexicon.json"))
noun_fr = set(LEX["NOUNS"]["fr"].keys()) | set(LEX["NOUNS"]["fr"].values())
noun_nl = set(LEX["NOUNS"]["nl"].keys()) | set(LEX["NOUNS"]["nl"].values())
verb_fr = {f for v in LEX["VERBS"].values() for f in v["fr"].values()}
verb_nl = {f for v in LEX["VERBS"].values() for f in v["nl"].values()}
part_fr = {v["part"]["fr"] for v in LEX["VERBS"].values()}
part_nl = {v["part"]["nl"] for v in LEX["VERBS"].values()}
aux_fr  = set(LEX["AUX"]["fr"].values())
aux_nl  = set(LEX["AUX"]["nl"].values())
TOK_FR  = noun_fr | verb_fr | part_fr | aux_fr | {"le","la","les"}
TOK_NL  = noun_nl | verb_nl | part_nl | aux_nl | {"de","het"}

def token_lang_frac(toks):
    tot = len(toks)
    return sum(t in TOK_FR for t in toks)/tot, sum(t in TOK_NL for t in toks)/tot

def word_order(toks):
    noun_v = noun_fr | noun_nl
    verb_v = verb_fr | verb_nl | part_fr | part_nl | aux_fr | aux_nl
    idx_n1 = next((i for i,t in enumerate(toks) if t in noun_v), None)
    if idx_n1 is None: return "unknown"
    idx_v = next((i for i in range(idx_n1+1, len(toks)) if toks[i] in verb_v), None)
    if idx_v is None: return "unknown"
    idx_n2 = next((i for i in range(idx_v+1, len(toks)) if toks[i] in noun_v), None)
    if idx_n2 is None: return "unknown"
    order = sorted([(idx_n1,"S"),(idx_v,"V"),(idx_n2,"O")], key=lambda x:x[0])
    return "".join(tag for _,tag in order)

# -------------------- full-test generation ---------------------------------
logger.info("Generating on test set")
model.eval()
gens = []
for r in test_df.itertuples():
    prompt = f"<sos> {r.input} <sep>"
    out = model.generate(
        **tokenizer(prompt, return_tensors="pt").to(device),
        max_new_tokens=20,
        eos_token_id=tokenizer.eos_token_id,
        num_beams=4
    )
    pred = tokenizer.decode(out[0], skip_special_tokens=False)\
           .split("<sep>")[1].replace("<eos>","").strip()
    gens.append({"input":r.input, "target":r.target,
                 "prediction":pred, "lang":r.lang})

df_gen = pd.DataFrame(gens)
df_gen.to_csv(OUT_DIR / "test_generations.csv", index=False)
logger.info("Test generations saved")

# -------------------- per-language evaluation ------------------------------
logger.info("Computing per-language metrics")
metrics = {
    "train_final_step": trainer.state.global_step,
    **trainer.state.log_history[-1]
}

for lang in ["fr","nl"]:
    sub = df_gen[df_gen.lang == lang]
    exact = (sub.prediction.str.strip() == sub.target.str.strip()).mean()
    fr_shares, nl_shares, orders = [], [], []
    for s in sub.prediction:
        toks = re.findall(r"\w+|[^\s\w]", s.lower())
        f_share, n_share = token_lang_frac(toks)
        fr_shares.append(f_share)
        nl_shares.append(n_share)
        orders.append(word_order(toks))
    oc = pd.Series(orders).value_counts(normalize=True)
    metrics.update({
        f"{lang}_exact":        float(exact),
        f"{lang}_avg_pred_fr":  float(np.mean(fr_shares)),
        f"{lang}_avg_pred_nl":  float(np.mean(nl_shares)),
        f"{lang}_order_SVO":    float(oc.get("SVO", 0.0)),
        f"{lang}_order_SOV":    float(oc.get("SOV", 0.0)),
        f"{lang}_order_other":  float(1.0 - oc.get("SVO", 0.0) - oc.get("SOV", 0.0))
    })

json.dump(metrics, open(OUT_DIR / "metrics.json", "w"), indent=2)
logger.info(f"✓ finished run p={prop:.1f}  outputs → {OUT_DIR}")

2025-05-22 10:24:08 INFO TenseTrainer: Logger initialized

2025-05-22 10:24:08 INFO TenseTrainer: Data dir: data, Output dir: weights/small_p30_run59
2025-05-22 10:24:08 INFO TenseTrainer: Loading CSVs
2025-05-22 10:24:09 INFO TenseTrainer: Train set: 38843 rows (14547 FR, 24296 NL)
2025-05-22 10:24:09 INFO TenseTrainer: Building tokenizer
2025-05-22 10:24:09 INFO TenseTrainer: Tokenizer vocab size: 368
2025-05-22 10:24:09 INFO TenseTrainer: Encoding dataset pairs
2025-05-22 10:24:16 INFO TenseTrainer: Train dataset size: 38843; Val dataset size: 12158
2025-05-22 10:24:16 INFO TenseTrainer: Creating Seq2SeqPadCollator
2025-05-22 10:24:16 INFO TenseTrainer: Initializing model
2025-05-22 10:24:16 INFO TenseTrainer: Defining metrics
2025-05-22 10:24:16 INFO TenseTrainer: Setting up Trainer
/n/home06/drooryck/circuits_languages_2/venv39/lib/python3.10/site-packages/accelerate/accelerator.py:449: FutureWarning: `torch.cuda.amp.GradScaler(args...)` is deprecated. Please use `torch.amp.GradScaler('cuda', args...)` instead.
  self.scaler = torch.cuda.amp.GradScaler(**kwargs)
2025-05-22 10:24:16 WARNING accelerate.utils.other: Detected kernel version 4.18.0, which is below the recommended minimum of 5.5.0; this can cause the process to hang. It is recommended to upgrade the kernel to the minimum version or higher.
2025-05-22 10:24:16 INFO TenseTrainer: Starting training

There were missing keys in the checkpoint model loaded: ['lm_head.weight'].
2025-05-22 10:25:20 INFO TenseTrainer: Training complete; saving model and tokenizer
2025-05-22 10:25:20 INFO TenseTrainer: Loading lexicon for post-hoc metrics
2025-05-22 10:25:20 INFO TenseTrainer: Generating on test set
2025-05-22 10:30:11 INFO TenseTrainer: Test generations saved
2025-05-22 10:30:11 INFO TenseTrainer: Computing per-language metrics
2025-05-22 10:30:11 INFO TenseTrainer: ✓ finished run p=0.3  outputs → weights/small_p30_run59

In [3]:
#!/usr/bin/env python
# ---------------------------------------------------------------------------
# Tiny GPT-2 tense-conversion trainer + per-language word-order / token-share
# ---------------------------------------------------------------------------

import argparse
import json
import re
import numpy as np
import pandas as pd
import torch
import logging
from pathlib import Path
from tokenizers import Tokenizer
from tokenizers.models import WordLevel
from tokenizers.pre_tokenizers import Whitespace
from tokenizers.decoders import WordPiece
from transformers import (
    PreTrainedTokenizerFast,
    GPT2Config, GPT2LMHeadModel,
    Trainer, TrainingArguments,
    EarlyStoppingCallback, set_seed
)

# -------------------- Logging Setup ---------------------------------------
logging.basicConfig(
    level=logging.INFO,
    format="%(asctime)s %(levelname)s: %(message)s",
    datefmt="%Y-%m-%d %H:%M:%S"
)
logger = logging.getLogger("TenseTrainer")
logger.info("Logger initialized")

# -------------------- CLI (commented out) ---------------------------------
# cli = argparse.ArgumentParser()
# cli.add_argument("--prop",   type=float, required=True, help="fraction of French data")
# cli.add_argument("--run_id", type=int,   required=True, help="random seed / run tag")
# args   = cli.parse_args()
# prop   = args.prop
# run_id = args.run_id
# -------------------- fixed params for this run ---------------------------
prop, run_id = 0.3, 65

# -------------------- RNG & paths -----------------------------------------
set_seed(run_id)
DATA_DIR = Path("data")
OUT_DIR  = Path(f"weights/small_p{int(prop*100):02d}_run{run_id}")
OUT_DIR.mkdir(parents=True, exist_ok=True)
logger.info(f"Run parameters: prop={prop}, run_id={run_id}")
logger.info(f"Data directory: {DATA_DIR}, Output directory: {OUT_DIR}")

# -------------------- load & split data -----------------------------------
train_full = pd.read_csv(DATA_DIR / "train.csv")

test_full = pd.read_csv(DATA_DIR/"test.csv")
# only use X% of it for evaluation
eval_prop = 0.1  # e.g. 20%
test_df = test_full.sample(frac=eval_prop, random_state=run_id).reset_index(drop=True)
logger.info(f"Evaluating on {len(test_df)} = {eval_prop*100:.0f}% of the test set")

df_fr = train_full[train_full.lang == "fr"]
df_nl = train_full[train_full.lang == "nl"]
want_fr = min(int(len(train_full) * prop), len(df_fr))
want_nl = min(len(train_full) - want_fr, len(df_nl))
train_df = pd.concat([
    df_fr.sample(want_fr, random_state=run_id),
    df_nl.sample(want_nl, random_state=run_id)
]).sample(frac=1, random_state=run_id).reset_index(drop=True)
logger.info(f"Train set size: {len(train_df)} ({want_fr} FR, {want_nl} NL)")

# -------------------- tokenizer --------------------------------------------
vocab = json.load(open(DATA_DIR / "vocab.json", encoding="utf-8"))
for sp in ["<pad>", "<sos>", "<eos>", "<sep>", "<unk>"]:
    if sp not in vocab:
        vocab.append(sp)
stoi = {t: i for i, t in enumerate(vocab)}

tok_obj = Tokenizer(WordLevel(stoi, unk_token="<unk>"))
tok_obj.pre_tokenizer = Whitespace()
tok_obj.decoder = WordPiece()
tokenizer = PreTrainedTokenizerFast(
    tokenizer_object=tok_obj,
    bos_token="<sos>", eos_token="<eos>",
    pad_token="<pad>", unk_token="<unk>", sep_token="<sep>"
)
logger.info(f"Tokenizer built (vocab size: {len(vocab)})")

# -------------------- dataset & collator -------------------------------
def encode_pair(pres, past):
    pres_ids = tokenizer.encode(pres, add_special_tokens=False)
    past_ids = tokenizer.encode(past, add_special_tokens=False)
    ids = [tokenizer.bos_token_id] + pres_ids + [tokenizer.sep_token_id] + past_ids + [tokenizer.eos_token_id]
    sep_pos = 1 + len(pres_ids)
    labels = [-100] * (sep_pos + 1) + ids[sep_pos+1:]
    if len(labels) < len(ids):
        labels += [-100] * (len(ids) - len(labels))
    return {"input_ids": ids, "attention_mask": [1] * len(ids), "labels": labels}

class PairDS(torch.utils.data.Dataset):
    def __init__(self, df):
        self.buf = [encode_pair(r.input, r.target) for r in df.itertuples()]
    def __len__(self):
        return len(self.buf)
    def __getitem__(self, i):
        return self.buf[i]

train_ds, val_ds = PairDS(train_df), PairDS(test_df)
logger.info(f"Datasets: train={len(train_ds)}, val={len(val_ds)}")

class Seq2SeqPadCollator:
    def __init__(self, tokenizer, pad_to_multiple_of=8):
        self.tokenizer = tokenizer
        self.pad_to_multiple_of = pad_to_multiple_of

    def __call__(self, features):
        max_len = max(len(f["input_ids"]) for f in features)
        if self.pad_to_multiple_of:
            max_len = ((max_len + self.pad_to_multiple_of - 1)
                       // self.pad_to_multiple_of) * self.pad_to_multiple_of
        batch = {
            "input_ids": torch.tensor(
                [f["input_ids"] + [self.tokenizer.pad_token_id] * (max_len - len(f["input_ids"]))
                 for f in features], dtype=torch.long),
            "attention_mask": torch.tensor(
                [f["attention_mask"] + [0] * (max_len - len(f["attention_mask"]))
                 for f in features], dtype=torch.long),
            "labels": torch.tensor(
                [f["labels"] + [-100] * (max_len - len(f["labels"]))
                 for f in features], dtype=torch.long),
        }
        return batch

collator = Seq2SeqPadCollator(tokenizer, pad_to_multiple_of=8)

# -------------------- model & metrics --------------------------------------
device = "cuda" if torch.cuda.is_available() else "cpu"
model = GPT2LMHeadModel(GPT2Config(
    vocab_size=len(vocab),
    n_embd=128, n_layer=2, n_head=2,
    bos_token_id=tokenizer.bos_token_id,
    eos_token_id=tokenizer.eos_token_id,
    pad_token_id=tokenizer.pad_token_id
)).to(device)

def tok_acc(eval_pred):
    logits, labels = eval_pred
    preds = np.argmax(logits[:, :-1], axis=-1)
    lbls = labels[:, 1:]
    mask = lbls != -100
    return {"tok_acc": float(((preds == lbls) & mask).sum() / mask.sum())}

def exact_match(eval_pred):
    logits, labels = eval_pred
    ok = ((np.argmax(logits[:, :-1], axis=-1) == labels[:, 1:]) |
          (labels[:, 1:] == -100)).all(axis=1)
    return {"exact_match": float(ok.mean())}

# -------------------- Trainer & train --------------------------------------
trainer = Trainer(
    model=model,
    args=TrainingArguments(
        output_dir=str(OUT_DIR),
        max_steps=200,
        per_device_train_batch_size=16,
        per_device_eval_batch_size=16,
        gradient_accumulation_steps=4,
        fp16=True,
        learning_rate=2e-4,
        warmup_steps=500,
        lr_scheduler_type="cosine",
        weight_decay=1e-2,
        eval_strategy="steps",
        eval_steps=1000,
        save_strategy="steps",
        save_steps=1000,
        save_total_limit=5,
        logging_steps=2000,
        load_best_model_at_end=True,
        metric_for_best_model="tok_acc",
        report_to="none"
    ),
    train_dataset=train_ds,
    eval_dataset=val_ds,
    data_collator=collator,
    compute_metrics=lambda ep: {**tok_acc(ep), **exact_match(ep)},
    callbacks=[EarlyStoppingCallback(early_stopping_patience=5)]
)

logger.info("Starting training")
trainer.train()
logger.info("Training complete; saving model")
trainer.save_model(OUT_DIR / "final")
tokenizer.save_pretrained(OUT_DIR / "final")

# -------------------- inference & save generations -------------------------
logger.info("Generating on test set")
model.eval()
gens = []
for r in test_df.itertuples():
    prompt = f"<sos> {r.input} <sep>"
    with torch.no_grad():
        out = model.generate(
            **tokenizer(prompt, return_tensors="pt").to(device),
            max_new_tokens=20,
            do_sample=False,
            num_beams=4,
            eos_token_id=tokenizer.eos_token_id
        )
    pred = tokenizer.decode(out[0], skip_special_tokens=False)\
               .split("<sep>")[1].replace("<eos>", "").strip()
    gens.append({
        "input": r.input,
        "target": r.target,
        "prediction": pred,
        "lang": r.lang
    })

df_gen = pd.DataFrame(gens)
df_gen.to_csv(OUT_DIR / "test_generations.csv", index=False)
logger.info("Test generations saved")

# -------------------- post-hoc metrics --------------------------------------
logger.info("Computing per-language metrics")
LEX = json.load(open("data/lexicon.json", encoding="utf-8"))
noun_fr = set(LEX["NOUNS"]["fr"].keys())   | set(LEX["NOUNS"]["fr"].values())
noun_nl = set(LEX["NOUNS"]["nl"].keys())   | set(LEX["NOUNS"]["nl"].values())
verb_fr = {f for v in LEX["VERBS"]["fr"].values() for f in v["present"].values()}
verb_nl = {f for v in LEX["VERBS"]["nl"].values() for f in v["present"].values()}
part_fr = {v["participle"] for v in LEX["VERBS"]["fr"].values()}
part_nl = {v["participle"] for v in LEX["VERBS"]["nl"].values()}
aux_fr  = set(LEX["AUX"]["fr"].values())
aux_nl  = set(LEX["AUX"]["nl"].values())

def token_lang_frac(toks):
    total = len(toks)
    return sum(t in noun_fr|verb_fr|part_fr|aux_fr for t in toks)/total, \
           sum(t in noun_nl|verb_nl|part_nl|aux_nl for t in toks)/total

def word_order(toks):
    noun_v = noun_fr|noun_nl
    verb_v = verb_fr|verb_nl|part_fr|part_nl|aux_fr|aux_nl
    idx_n1=idx_v=idx_n2=None
    for i,t in enumerate(toks):
        if t in noun_v: idx_n1=i; break
    if idx_n1 is None: return "unknown"
    for i in range(idx_n1+1,len(toks)):
        if toks[i] in verb_v: idx_v=i; break
    if idx_v is None: return "unknown"
    for i in range(idx_v+1,len(toks)):
        if toks[i] in noun_v: idx_n2=i; break
    if idx_n2 is None: return "unknown"
    return "".join(tag for _,tag in sorted([(idx_n1,"S"),(idx_v,"V"),(idx_n2,"O")], key=lambda x:x[0]))

def is_participle_final(tokens, lang):
    if lang == "fr":
        nouns, parts, auxes = noun_fr, part_fr, aux_fr
    else:
        nouns, parts, auxes = noun_nl, part_nl, aux_nl
    noun_idxs = [i for i,t in enumerate(tokens) if t in nouns]
    part_idxs = [i for i,t in enumerate(tokens) if t in parts]
    aux_idxs  = [i for i,t in enumerate(tokens) if t in auxes]
    if len(noun_idxs) < 2 or not part_idxs or not aux_idxs:
        return False
    obj_idx = noun_idxs[1]
    return max(part_idxs) > obj_idx

metrics = {
    "train_final_step": trainer.state.global_step,
    **trainer.state.log_history[-1]
}

for lang in ("fr", "nl"):
    sub = df_gen[df_gen.lang == lang]
    exact = (sub.prediction.str.strip() == sub.target.str.strip()).mean()
    fr_shares, nl_shares, orders, part_finals = [], [], [], []
    for s in sub.prediction:
        toks = re.findall(r"\w+|[^\s\w]", s.lower())
        f, n = token_lang_frac(toks)
        fr_shares.append(f)
        nl_shares.append(n)
        orders.append(word_order(toks))
        part_finals.append(is_participle_final(toks, lang))
    oc = pd.Series(orders).value_counts(normalize=True)
    metrics.update({
        f"{lang}_exact":           float(exact),
        f"{lang}_avg_pred_fr":     float(np.mean(fr_shares)),
        f"{lang}_avg_pred_nl":     float(np.mean(nl_shares)),
        f"{lang}_order_SVO":       float(oc.get("SVO", 0.0)),
        f"{lang}_order_SOV":       float(oc.get("SOV", 0.0)),
        f"{lang}_order_other":     float(1.0 - oc.get("SVO", 0.0) - oc.get("SOV", 0.0)),
        f"{lang}_part_final_frac": float(np.mean(part_finals))
    })

json.dump(metrics, open(OUT_DIR / "metrics.json", "w", encoding="utf-8"),
          ensure_ascii=False, indent=2)
logger.info(f"✓ finished run p={prop:.1f}, run_id={run_id}, outputs → {OUT_DIR}")

2025-05-23 12:21:15 INFO: Logger initialized
2025-05-23 12:21:15 INFO: Run parameters: prop=0.3, run_id=65
2025-05-23 12:21:15 INFO: Data directory: data, Output directory: weights/small_p30_run65
2025-05-23 12:21:15 INFO: Evaluating on 1216 = 10% of the test set
2025-05-23 12:21:15 INFO: Train set size: 38843 (14547 FR, 24296 NL)
/n/home06/drooryck/circuits_languages_2/.venv/lib64/python3.11/site-packages/transformers/tokenization_utils_base.py:1601: FutureWarning: `clean_up_tokenization_spaces` was not set. It will be set to `True` by default. This behavior will be depracted in transformers v4.45, and will be then set to `False` by default. For more details check this issue: https://github.com/huggingface/transformers/issues/31884
  warnings.warn(
2025-05-23 12:21:15 INFO: Tokenizer built (vocab size: 368)
2025-05-23 12:21:16 INFO: Datasets: train=38843, val=1216
2025-05-23 12:21:16 WARNING: Detected kernel version 4.18.0, which is below the recommended minimum of 5.5.0; this can cause the process to hang. It is recommended to upgrade the kernel to the minimum version or higher.
max_steps is given, it will override any value given in num_train_epochs
2025-05-23 12:21:16 INFO: Starting training

2025-05-23 12:21:25 INFO: Training complete; saving model
2025-05-23 12:21:25 INFO: Generating on test set
2025-05-23 12:21:36 INFO: Test generations saved
2025-05-23 12:21:36 INFO: Computing per-language metrics
2025-05-23 12:21:36 INFO: ✓ finished run p=0.3, run_id=65, outputs → weights/small_p30_run65